### ISSUE TITLE
String to float culture info problem

### ISSUE THREAD

**Issue by xiaoxiao921** [kylepaulsen/RoR2-Original-Sound-Track#1]
Hi, depending on the country you are in, the `System.Globalization.CultureInfo` used by the computer isnt the same, in my case, float.parse except the seperator to be a comma, not a dot, so it fails parsing correctly the string and stacktrace the plugin. A lot of users could be affected

here is a test program showing the problem

```cs
using System;
					
public class Program
{
	public static void Main()
	{
		string test = "0.5";
		System.Globalization.CultureInfo frFr = new System.Globalization.CultureInfo("fr-FR");
		//var f = Single.Parse(test, System.Globalization.CultureInfo.InvariantCulture); works cause it use the default aka US i think
		var f = Single.Parse(test, frFr); // doesnt work it except a commat 0,5
		Console.Write(f);
	}
}
```

**Comment by kylepaulsen** [comment]
@xiaoxiao921 This should be fixed now in v1.1.1 I think. Using `CultureInfo.InvariantCulture` to parse like you suggested so values in the settings.xml must be in this form: `0.52`.
