### ISSUE TITLE
Plugin is selecting music at random

### ISSUE THREAD

**Issue by Squatlock** [kylepaulsen/RoR2-Original-Sound-Track#6]
Hello, I am trying to add the 2nd games soundtrack in with the first, but after adding them into the xml it is now just randomly selecting a song to play, completely ignoring the scene tag. I've look though the XML a few times and it seems to be formatted right, and all the names  match up with the file names. Have I done something wrong? 
[settings.docx](https://github.com/kylepaulsen/RoR2-Original-Sound-Track/files/5173147/settings.docx)

**Comment by kylepaulsen** [comment]
So first thing I notice is that file should be a `.xml` file, not a `.docx`... You might need a text editor like [VSCode](https://code.visualstudio.com/) or [Notepad++](https://notepad-plus-plus.org/) (as a more lightweight editor) and make sure you save as "settings.xml". Windows hides extensions sometimes so maybe [unhide them](https://www.howtogeek.com/205086/beginner-how-to-make-windows-show-file-extensions/) if you are unsure.
Second thing I noticed is that you might have a syntax error in your xml file. Looks like you are missing a quote on the boss attribute in this entry:
```
<song
    name="18 con lentitud poderosa.mp3"
    scenes="moon"
    boss="false
    volume="1"
/>
```
You can use an xml validator like [this one](https://www.xmlvalidation.com/) to make sure the xml code is correct.

**Comment by Squatlock** [comment]
Thanks for the help, I didn't notice the error! Great mod btw!
